import type { Monaco } from '@monaco-editor/react';

// Minimal Monarch tokenizer for Verilog-2001 / SystemVerilog. This is
// syntax-highlighting only — no semantic analysis. PR #6+ can swap in a real
// language server (e.g. veridian / svls) if we decide we need symbol search,
// goto-def, etc.
const VERILOG_KEYWORDS = [
  'always',
  'always_comb',
  'always_ff',
  'always_latch',
  'and',
  'assign',
  'automatic',
  'begin',
  'break',
  'case',
  'casex',
  'casez',
  'class',
  'const',
  'continue',
  'default',
  'defparam',
  'do',
  'else',
  'end',
  'endcase',
  'endclass',
  'endfunction',
  'endgenerate',
  'endinterface',
  'endmodule',
  'endpackage',
  'endprogram',
  'endtask',
  'enum',
  'extern',
  'final',
  'for',
  'foreach',
  'forever',
  'fork',
  'function',
  'generate',
  'genvar',
  'if',
  'initial',
  'inout',
  'input',
  'integer',
  'interface',
  'join',
  'join_any',
  'join_none',
  'localparam',
  'logic',
  'longint',
  'module',
  'modport',
  'negedge',
  'new',
  'output',
  'package',
  'packed',
  'parameter',
  'posedge',
  'program',
  'property',
  'pure',
  'rand',
  'randc',
  'real',
  'reg',
  'repeat',
  'return',
  'shortint',
  'signed',
  'static',
  'string',
  'struct',
  'supply0',
  'supply1',
  'task',
  'time',
  'tri',
  'typedef',
  'union',
  'unique',
  'unsigned',
  'virtual',
  'void',
  'wait',
  'wand',
  'while',
  'wire',
  'wor',
];

const VERILOG_TYPE_KEYWORDS = ['bit', 'byte', 'chandle', 'event', 'shortreal'];

export function registerVerilogLanguage(monaco: Monaco): void {
  for (const id of ['verilog', 'systemverilog'] as const) {
    const already = monaco.languages.getLanguages().some((l: { id: string }) => l.id === id);
    if (already) continue;
    monaco.languages.register({ id, extensions: id === 'verilog' ? ['.v'] : ['.sv', '.svh'] });
    monaco.languages.setLanguageConfiguration(id, {
      comments: { lineComment: '//', blockComment: ['/*', '*/'] },
      brackets: [
        ['{', '}'],
        ['[', ']'],
        ['(', ')'],
      ],
      autoClosingPairs: [
        { open: '{', close: '}' },
        { open: '[', close: ']' },
        { open: '(', close: ')' },
        { open: '"', close: '"' },
      ],
    });
    monaco.languages.setMonarchTokensProvider(id, {
      defaultToken: '',
      tokenPostfix: `.${id}`,
      keywords: [...VERILOG_KEYWORDS, ...VERILOG_TYPE_KEYWORDS],
      operators: [
        '=',
        '<=',
        '==',
        '===',
        '!=',
        '!==',
        '<',
        '>',
        '<=',
        '>=',
        '&&',
        '||',
        '!',
        '~',
        '&',
        '|',
        '^',
        '<<',
        '>>',
        '+',
        '-',
        '*',
        '/',
        '%',
        '?',
        ':',
      ],
      symbols: /[=><!~?:&|+\-*/^%]+/,
      tokenizer: {
        root: [
          [/`[A-Za-z_]\w*/, 'keyword.directive'],
          [/\$[A-Za-z_]\w*/, 'support.function.system'],
          [
            /[A-Za-z_]\w*/,
            {
              cases: {
                '@keywords': 'keyword',
                '@default': 'identifier',
              },
            },
          ],
          [/\d+'[bB][01xzXZ_?]+/, 'number.binary'],
          [/\d+'[oO][0-7xzXZ_?]+/, 'number.octal'],
          [/\d+'[hH][0-9a-fA-FxzXZ_?]+/, 'number.hex'],
          [/\d+'[dD][0-9_]+/, 'number'],
          [/\d+\.\d+/, 'number.float'],
          [/\d+/, 'number'],
          [/"([^"\\]|\\.)*$/, 'string.invalid'],
          [/"/, 'string', '@string'],
          [/\/\/.*$/, 'comment'],
          [/\/\*/, 'comment', '@comment'],
          [/[{}[\]()]/, '@brackets'],
          [/@symbols/, { cases: { '@operators': 'operator', '@default': '' } }],
          [/[;,.]/, 'delimiter'],
          [/\s+/, 'white'],
        ],
        string: [
          [/[^\\"]+/, 'string'],
          [/\\./, 'string.escape'],
          [/"/, 'string', '@pop'],
        ],
        comment: [
          [/[^/*]+/, 'comment'],
          [/\*\//, 'comment', '@pop'],
          [/[/*]/, 'comment'],
        ],
      },
    });
  }
}
